---
abstract: 'Simplify data structures for naive serialization.'
author:
  - 'Mark Swayne <daotoad@cpan.org>'
build_requires:
  Data::Dumper: 0
  Storable: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Abridge
no_index:
  directory:
    - t
    - inc
requires:
  B: 0
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
  constant: 0
  overload: 0
version: v0.03.01
